<a href="https://colab.research.google.com/github/Danielmejiava/danielmejiava.github.io/blob/main/WorkforceBrisbane.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
import matplotlib as mpl
mpl.rcParams['figure.figsize'] = [16.0,8.0]

In [ ]:
from google.colab import drive
df1 = pd.read_excel('/content/6291002-2.xlsx','Data2')

df2 =df1.drop(df1.index[0:9])

In [ ]:
df2.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)
df2["Date"] = pd.to_datetime(df2["Date"])
df2['Year'] = df2['Date'].dt.year
df2 = pd.concat([df2.iloc[:, 87:168], df2.iloc[:, -1]], axis=1)

df2.head(50)

,>> Greater Brisbane ; Employed total ; Persons ;,>> Greater Brisbane ; Employed total ; > Males ;,>> Greater Brisbane ; Employed total ; > Females ;,>> Greater Brisbane ; > Employed full-time ; Persons ;,>> Greater Brisbane ; > Employed full-time ; > Males ;,>> Greater Brisbane ; > Employed full-time ; > Females ;,>> Greater Brisbane ; > Employed part-time ; Persons ;,>> Greater Brisbane ; > Employed part-time ; > Males ;,>> Greater Brisbane ; > Employed part-time ; > Females ;,>> Greater Brisbane ; Employment to population ratio ; Persons ;,...,>> Rest of Qld ; Labour force total ; Persons ;,>> Rest of Qld ; Labour force total ; > Males ;,>> Rest of Qld ; Labour force total ; > Females ;,>> Rest of Qld ; Participation rate ; Persons ;,>> Rest of Qld ; Participation rate ; > Males ;,>> Rest of Qld ; Participation rate ; > Females ;,>> Rest of Qld ; Not in the labour force (NILF) ; Persons ;,>> Rest of Qld ; Not in the labour force (NILF) ; > Males ;,>> Rest of Qld ; Not in the labour force (NILF) ; > Females ;,Year
9,634.502152,361.948034,272.554118,501.665314,330.431287,171.234027,132.836838,31.516748,101.32009,57.938524,...,727.925805,435.442211,292.483594,61.631592,73.804265,49.481572,453.166195,154.553789,298.612406,1991
10,638.608279,367.039541,271.568738,499.044584,331.387248,167.657335,139.563695,35.652293,103.911402,58.223617,...,724.976101,432.927739,292.048361,61.247074,73.218116,49.298684,458.714899,158.357261,300.357639,1991
11,646.374807,371.500244,274.874562,504.325939,335.08491,169.241029,142.048867,36.415334,105.633533,58.842281,...,739.390881,442.512877,296.878004,62.32874,74.676643,50.00438,446.885119,150.059123,296.825996,1991
12,646.444496,373.763315,272.681181,508.019969,340.564041,167.455928,138.424527,33.199274,105.225253,58.756411,...,729.872154,436.489558,293.382596,61.388373,73.49237,49.306591,459.069846,157.435442,301.634404,1991
13,647.611867,374.34274,273.269127,505.525644,337.406428,168.119216,142.086222,36.936312,105.149911,58.770317,...,730.977689,435.199314,295.778376,61.343393,73.107233,49.600031,460.638311,160.089686,300.548625,1991
14,655.910027,375.845438,280.06459,516.33394,340.034243,176.299697,139.576087,35.811194,103.764892,59.430497,...,751.365237,447.682565,303.682672,62.913395,75.033574,50.813476,442.919763,148.960435,293.959328,1991
15,634.849023,366.91366,267.935363,510.643614,333.713073,176.930541,124.205409,33.200588,91.004822,57.403984,...,742.874027,445.339814,297.534212,62.035254,74.434946,49.654497,454.628973,152.954185,301.674788,1992
16,648.356772,369.819717,278.537056,502.293644,330.623504,171.67014,146.063129,39.196213,106.866916,58.505182,...,757.748241,447.934606,309.813635,63.106403,74.66087,51.56788,442.998759,152.024394,290.974365,1992
17,651.676958,373.157881,278.519077,499.518224,333.611284,165.90694,152.158734,39.546596,112.612137,58.684206,...,755.159182,446.722783,308.436399,62.722425,74.254424,51.204746,448.810818,154.888217,293.922601,1992
18,657.899004,374.946749,282.952255,506.525138,335.673117,170.852021,151.373866,39.273632,112.100234,59.173158,...,751.194152,446.458492,304.73566,62.277589,74.073578,50.496398,455.008848,156.264508,298.74434,1992
19,655.258488,372.430637,282.827851,503.574509,329.007537,174.566971,151.683979,43.4231,108.260879,58.864665,...,750.692556,444.768757,305.923799,62.121928,73.658309,50.600124,457.725444,159.058243,298.667201,1992
20,652.900243,369.578891,283.321351,499.720151,328.951894,170.768257,153.180092,40.626998,112.553095,58.582293,...,754.282416,447.572572,306.709844,62.303869,73.986275,50.636334,456.368584,157.367428,299.001156,1992
21,654.337045,372.34351,281.993535,502.756804,335.306125,167.450679,151.580242,37.037386,114.542856,58.608299,...,760.931895,453.723492,307.208402,62.700852,74.821982,50.595352,452.659105,152.680508,299.978598,1992
22,649.818932,365.287136,284.531797,490.764458,325.134344,165.630114,159.054474,40.152792,118.901683,58.101616,...,754.899119,447.821892,307.077227,62.054392,73.670668,50.452849,461.612881,160.048108,301.564773,1992
23,657.783123,369.277233,288.50589,496.147506,328.662519,167.484987,161.635618,40.614715,121.020903,58.711188,...,776.057805,454.943486,321.114319,63.639986,74.662784,52.631424,443.392195,154.387514,289.004681,1992
24,657.085668,370.700352,286.385317,498.923431,331.59983,167.323601,158.162238,39.100522,119.061716,58.554287,...,769.981848,452.504249,317.477599,62.998423,74.093327,51.917671,452.242152,158.217751,294.024401,1992
25,657.74241,368.016273,289.726137,500.53242,331.328678,169.203742,157.20999,36.687595,120.522395,58.518581,...,763.269641,452.382595,310.887045,62.306607,73.902543,50.724936,461.752359,159.751405,302.000954,1992
26,667.578425,377.22091,290.357515,511.560096,340.44141,171.118686,156.018329,36.7795,119.238829,59.297926,...,775.406507,459.64909,315.757417,63.154292,74.919252,51.403602,452.390492,153.87691,298.513583,1992
27,656.585971,372.501711,284.08426,509.720338,332.89097,176.829367,146.865634,39.610741,107.254893,58.176,...,764.444182,458.345181,306.099001,62.065867,74.466282,49.678573,467.221818,157.161819,310.059999,1993
28,657.387778,372.719869,284.667909,502.028915,332.259999,169.768915,155.358864,40.45987,114.898994,58.102793,...,766.924547,458.461818,308.462728,62.071962,74.246031,49.908944,468.616453,159.028182,309.588272,1993
29,668.511069,378.031054,290.480015,515.422028,340.322042,175.099986,153.089041,37.709011,115.38003,58.939068,...,783.781385,461.994384,321.787001,63.238265,74.578735,51.90632,455.628615,157.477616,298.150999,1993
30,660.786613,372.977118,287.809496,504.954048,335.112309,169.841739,155.832566,37.864809,117.967757,58.173878,...,772.772491,461.421318,311.351173,62.218805,74.32569,50.119793,469.251509,159.388682,309.862827,1993
31,659.456035,372.567657,286.888377,509.322802,337.053126,172.269676,150.133232,35.514531,114.618701,57.973036,...,775.265594,463.137206,312.128388,62.28804,74.442004,50.141026,469.380406,159.007794,310.372612,1993
32,660.631814,378.615039,282.016776,508.660862,339.604205,169.056657,151.970952,39.010833,112.960119,57.992534,...,781.607053,467.230776,314.376277,62.665576,74.938455,50.398502,465.659947,156.255224,309.404723,1993
33,660.653313,381.865976,278.787337,517.999531,344.378816,173.620715,142.653782,37.48716,105.166622,57.874777,...,782.834962,464.123021,318.711941,62.61192,74.256832,50.971646,467.462038,160.900979,306.561059,1993
34,664.249422,381.322888,282.926534,507.602189,340.296441,167.305749,156.647233,41.026447,115.620785,58.069649,...,766.071269,454.746501,311.324768,61.123163,72.578401,49.67169,487.252731,171.812499,315.440232,1993
35,680.719449,387.305515,293.413934,517.915437,345.443703,172.471734,162.804012,41.861812,120.9422,59.387373,...,791.65078,465.326577,326.324203,63.011861,74.084792,51.94161,464.70122,162.773423,301.927797,1993
36,674.212688,385.678362,288.534326,516.370158,344.873134,171.497023,157.842531,40.805227,117.037303,58.725901,...,786.685338,463.975326,322.710013,62.49387,73.727509,51.263765,472.134662,165.335674,306.798987,1993
37,667.169841,380.937199,286.232641,510.037516,342.81198,167.225536,157.132325,38.125219,119.007105,58.019612,...,791.699299,465.452702,326.246597,62.768964,73.819982,51.722204,469.591701,165.071298,304.520403,1993
38,682.111338,386.159366,295.951971,527.51559,349.642217,177.873373,154.595748,36.517149,118.078598,59.224472,...,806.086795,470.958437,335.128358,63.785002,74.550117,53.024793,457.669205,160.775563,296.893642,1993
39,671.919746,388.573767,283.345979,522.103686,345.249006,176.85468,149.81606,43.324761,106.491299,58.211107,...,797.304679,475.491049,321.81363,62.927304,75.065129,50.792335,469.720321,157.946951,311.77337,1994
40,680.391815,388.318177,292.073637,518.917539,344.189015,174.728523,161.474276,44.129162,117.345114,58.8155,...,800.833217,470.74667,330.086547,63.043338,74.11606,51.970512,469.456783,164.40133,305.055453,1994
41,691.358295,392.350244,299.00805,527.208301,348.117432,179.090869,164.149993,44.232812,119.917181,59.632239,...,804.178684,470.107084,334.0716,63.144154,73.817089,52.468738,469.381316,166.746916,302.6344,1994
42,683.589724,389.193629,294.396095,525.857365,347.571155,178.286211,157.732359,41.622474,116.109885,58.871075,...,805.770333,472.531316,333.239017,63.149679,74.057041,52.239599,470.198667,165.532684,304.665983,1994
43,689.836307,392.508768,297.327539,525.444218,348.114779,177.329439,164.392089,44.39399,119.9981,59.317592,...,805.227306,472.827769,332.399537,62.987955,73.962662,52.010242,473.155694,166.451231,306.704463,1994
44,687.769764,389.89111,297.878654,533.314503,349.388586,183.925917,154.455261,40.502524,113.952737,59.048855,...,812.993688,479.764549,333.22914,63.475757,74.905861,52.042333,467.800312,160.725451,307.07486,1994
45,697.65128,396.682958,300.968322,531.142507,353.284934,177.857573,166.508773,43.398023,123.110749,59.780269,...,805.237605,475.794499,329.443107,62.746195,74.141088,51.348478,478.087395,165.947501,312.139893,1994
46,693.165371,394.669765,298.495607,531.164424,351.885064,179.27936,162.000947,42.7847,119.216247,59.280877,...,807.441354,474.689369,332.751985,62.794171,73.824737,51.76127,478.412646,168.305631,310.107015,1994
47,710.601365,398.769488,311.831877,536.084677,355.278641,180.806035,174.516689,43.490847,131.025842,60.653769,...,827.366808,481.878177,345.48863,64.217159,74.796884,53.635643,461.022192,162.370823,298.65137,1994
48,710.367414,403.128491,307.238923,538.767048,359.307419,179.459629,171.600366,43.821072,127.779294,60.532583,...,811.240133,477.639711,333.600422,62.857937,74.009984,51.70328,479.352867,167.732289,311.620578,1994
49,713.412947,401.05737,312.355577,540.327389,358.247408,182.079981,173.085558,42.809962,130.275597,60.690531,...,815.106741,473.729708,341.377033,63.049766,73.277304,52.819395,477.692259,172.759292,304.932967,1994
50,729.174779,410.864523,318.310256,550.649835,365.682891,184.966944,178.524944,45.181632,133.343312,61.928669,...,820.990485,482.214772,338.775713,63.397047,74.460904,52.329463,474.007515,165.393228,308.614287,1994
51,701.284526,401.74422,299.540306,536.217303,362.05519,174.162113,165.067223,39.689029,125.378193,59.429734,...,813.103331,480.26311,332.84022,62.648093,73.986571,51.303427,484.786669,168.85889,315.92778,1995
52,716.934527,407.079771,309.854756,543.28951,364.661395,178.628115,173.645017,42.418376,131.226641,60.623022,...,836.744354,482.741179,354.003175,64.326107,74.195961,54.449043,464.040646,167.888821,296.151825,1995
53,729.226303,409.830331,319.395972,547.167813,362.645803,184.52201,182.05849,47.184528,134.873961,61.528219,...,835.2988,483.047753,352.251048,64.072527,74.070379,54.065208,468.3782,169.099247,299.278952,1995
54,718.739287,398.927931,319.811356,546.640676,356.359061,190.281615,172.098611,42.56887,129.529741,60.516852,...,845.022439,489.452273,355.570165,64.680414,74.890297,54.46021,461.435562,164.106727,297.328835,1995
55,720.610912,404.060181,316.550731,548.083706,359.201295,188.882411,172.527206,44.858886,127.66832,60.547958,...,840.801494,486.037696,354.763798,64.221068,74.20842,54.223092,468.428506,168.925304,299.503202,1995
56,733.824729,410.96161,322.863119,555.64498,364.970952,190.674029,178.179749,45.990658,132.189091,61.529957,...,840.113755,486.701607,353.412148,64.032914,74.150496,53.90396,471.889245,169.668393,302.220852,1995
57,729.516688,406.703214,322.813474,554.629066,360.207294,194.421772,174.887622,46.49592,128.391702,61.04451,...,836.931531,486.22979,350.701741,63.671227,73.93668,53.393239,477.526469,171.40021,306.126259,1995
58,720.526241,402.591033,317.935208,542.067149,353.192356,188.874793,178.459092,49.398677,129.060415,60.17006,...,831.18665,484.476745,346.709905,63.116627,73.530235,52.689473,485.71935,174.404255,311.315095,1995

In [ ]:
grouped_by_year = df2.groupby("Year")[[
    ">> Greater Brisbane ;  > Employed full-time ;  > Females ;",
    ">> Greater Brisbane ;  > Employed full-time ;  > Males ;",
    ">> Greater Brisbane ;  > Employed part-time ;  > Males ;",
    ">> Greater Brisbane ;  > Employed part-time ;  > Females ;",
]].sum()
grouped_by_year.head(50)

,>> Greater Brisbane ; > Employed full-time ; > Females ;,>> Greater Brisbane ; > Employed full-time ; > Males ;,>> Greater Brisbane ; > Employed part-time ; > Males ;,>> Greater Brisbane ; > Employed part-time ; > Females ;
Year,,,,
1991,1020.007233,2014.908157,209.531155,625.005082
1992,2038.906679,3984.053314,465.639635,1356.686464
1993,2062.860471,4084.688943,465.992811,1378.933109
1994,2154.66516,4226.316332,519.691959,1458.565357
1995,2261.284792,4339.675174,551.810592,1568.44347
1996,2311.379186,4433.485521,541.39663,1574.548251
1997,2282.294292,4333.957496,629.048297,1692.473867
1998,2354.095356,4424.059174,673.353724,1739.131098
1999,2364.684274,4538.131951,632.383919,1841.958199
2000,2471.428852,4583.905635,668.371702,1874.484775
2001,2450.044335,4519.213869,721.661941,1936.83107
2002,2597.016643,4751.999704,810.755227,1981.277547
2003,2687.898112,4893.761898,837.726947,2151.299427
2004,2878.723354,5092.456668,868.579922,2069.711128
2005,2980.48963,5312.238244,911.693568,2300.075714
2006,3090.245729,5518.417217,947.268294,2396.279506
2007,3260.851794,5779.926563,978.605599,2406.535007
2008,3457.795128,5960.550736,977.813007,2466.905733
2009,3523.019593,6042.655095,978.611619,2535.184487
2010,3510.358002,6043.753862,1103.22389,2614.873802
2011,3660.501931,6124.56213,1103.606323,2550.732297
2012,3638.517557,6163.418676,1131.454721,2581.617805
2013,3625.657538,6112.081582,1169.909742,2700.826026
2014,3584.119539,6110.610015,1241.092011,2860.901667
2015,3780.11978,6115.841699,1225.269871,2918.867551
2016,3889.354493,6229.41992,1306.228283,2899.802412
2017,3904.817348,6197.458991,1446.201261,3110.75661
2018,4102.26606,6314.129006,1500.1636,3057.394723
2019,4120.641065,6562.372213,1448.342777,3170.439776
2020,4054.997608,6266.311482,1456.135437,3094.504114
2021,4304.773135,6703.661836,1592.34995,3249.784087
2022,4715.754399,7057.842254,1554.665124,3383.200238
2023,4919.65135,7302.352662,1606.877891,3428.930148
2024,5264.89248,7408.562067,1757.423218,3614.234887

In [ ]:
# Columns to clean
columns_to_convert = [
    ">> Greater Brisbane ;  > Employed part-time ;  > Males ;",
    ">> Greater Brisbane ;  > Employed part-time ;  > Females ;",
    ">> Greater Brisbane ;  > Employed full-time ;  > Males ;",
    ">> Greater Brisbane ;  > Employed full-time ;  > Females ;",
]

for col in columns_to_convert:
    grouped_by_year[col] = pd.to_numeric(
        grouped_by_year[col].astype(str).str.replace(",", "").str.strip(),  # Remove commas and spaces
        errors="coerce"  # Convert invalid entries to NaN
    )

In [ ]:
import plotly.express as px

# Plot the data with Year as the x-axis
fig = px.line(
    grouped_by_year.reset_index(),  # Temporarily reset the index to access "Year"
    x="Year",
    y=[
        ">> Greater Brisbane ;  > Employed full-time ;  > Males ;",
        ">> Greater Brisbane ;  > Employed full-time ;  > Females ;",
        ">> Greater Brisbane ;  > Employed part-time ;  > Males ;",
        ">> Greater Brisbane ;  > Employed part-time ;  > Females ;",
    ],
    title="Employment Trends by Year in Greater Brisbane",
    labels={"value": "Number of Employees", "Year": "Year", "variable": "Category"},
)

fig.update_layout(
    xaxis_title="Year",
    yaxis_title="Number of Employees",
    legend_title="Categories",
    hovermode="x unified",
)

fig.show()

### Employment Trends in Greater Brisbane

This graph shows that both male and female full-time workforces in Greater Brisbane have been increasing over time. However, a key insight is that the gap between male and female full-time employment remains relatively constant throughout the entire period, indicating a persistent disparity in workforce participation.

This graph suggests that a significant portion of women in Brisbane hold part-time jobs. This trend could be attributed to factors such as maternity responsibilities or a preference for dedicating part of their time to household activities and caregiving duties. Furthermore, the combined number of women employed in both full-time and part-time roles appears to be similar to the total number of men employed full-time.

## Data Information:

https://www.abs.gov.au/statistics/labour/employment-and-unemployment/labour-force-australia-detailed/dec-2024